import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

interface Pokemon {
  name: string;
  id: number;
  image: string;
}

export async function getStaticProps() {
  const resp = await fetch("https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json")

  return {
    props: {
      pokemon: await resp.json()
    }
  }
}

export default function Home({ pokemon }: { pokemon: Pokemon[] }) {
  return (
    <div className={styles.main}>
      <Head>
        <title>use state</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        {pokemon.slice(0, 20).map((p) => (
          <div key={p.id} className={styles.image}>
            <img src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${p.image}`}  />
            <h2>{p.name}</h2>
          </div>
        ))}
      </div>      
    </div>
  )
}
