import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useMemo } from 'react'

interface Pokemon {
  name: string;
  id: number;
  image: string;
}

export async function getStaticProps() {
  const resp = await fetch("https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json")

  return {
    props: {
      pokemon: await resp.json()
    }
  }
}

export default function Home({ pokemon }: { pokemon: Pokemon[] }) {
  const [filtered, setFiltered] = useState("")

  // useMemo is a React hook that caches the result of a function call.
  // It's useful for caching the result of an expensive function call.
  // The function call is only made once, and the result is cached for future use.
  // If the function call is expensive, useMemo is a good choice.
  const filteredPokemon = useMemo(
    () => pokemon.filter((p) => p.name.toLowerCase().includes(filtered.toLowerCase())), [filtered])

  return (
    <div className={styles.main}>
      <Head>
        <title>use state</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <input type="text" value={filtered} onChange={(e) => setFiltered(e.target.value)} />
      <div className={styles.container}>
        {filteredPokemon.slice(0, 20).map((p) => (
          <div key={p.id} className={styles.image}>
            <img src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${p.image}`}  />
            <h2>{p.name}</h2>
          </div>
        ))}
      </div>      
    </div>
  )
}
